# Generated by Django 5.2.8 on 2025-11-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.FloatField(default=0.0, help_text='Calcium value', verbose_name='Ca')),
                ('mg', models.FloatField(default=0.0, help_text='Magnesium value', verbose_name='Mg')),
                ('na', models.FloatField(default=0.0, help_text='Sodium value', verbose_name='Na')),
                ('so4', models.FloatField(default=0.0, help_text='Sulfate value', verbose_name='SO4')),
                ('others', models.FloatField(default=0.0, help_text='Other combined value or 0.0 if none', verbose_name='Others')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Water Analysis',
                'verbose_name_plural': 'Water Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
